package edu.sjsu.cs.cs151.minesweeper.message;

import java.io.Serializable;

/**
 * Messages are used send events generated by the View class to the Controller class
 * The Message interface itself has no methods and is used to store and identify the classes that implement it
 */
public interface Message extends Serializable
{

}
